### PR TITLE
Remove `target_id` from `instances` table

### LINKED ISSUE #116: Batch filter update errors if it collides with itself
If the batch include expression is updated and the new filter is inclusive of any instances in the old filter, then the update will fail:
```
Received an error from the server: Failed updating batch "my-batch": Instance "my-instance" is already assigned to a batch
```

We should exempt any instances already in this batch from this validation.

### PR DESCRIPTION
**Pull request by masnax**
Closes #116

The target is a batch level concept so it doesn't need to be recorded in the instance table. An instance knows about its target through its associated batch ID.

By removing this column, we also fix an issue with updating batches where it is not possible to update any batches with instances in them, because we try to update the shared target ID column in both tables, but we disallow updating any instances already in a batch.

### CODE REVIEW

**Comment by stgraber** [comment]
I'll let @gibmat review this one.

In general I think we'll want to further evolve the relationship so that an `instance` is related to its `queue` entry which is then related to a `batch`.

That will enforce that no instance may be part of two batches and it will also allow us to have batches which dispatch instances to different targets and projects by moving those fields into the generated queue entry (see #89 for something that will add this extra bit of fun).

**Comment by stgraber** [comment]
@masnax sorry, the last PR I merged is causing a couple of conflicts in this one now.

File: internal/db/update.go [hunk 1]
```diff
@@ -146,7 +146,6 @@ CREATE TABLE instances (
     migration_status_string TEXT NOT NULL,
     last_update_from_source TEXT NOT NULL,
     source_id INTEGER NOT NULL,
-    target_id INTEGER NULL,
```
Comment (gibmat) [inline internal/db/update.go:149]: Also remove from line 36

**Review by gibmat — APPROVED** [review]

File: internal/db/update.go (hunk 1 above)
Comment (stgraber) [reply internal/db/update.go:149]: Ah yeah, @masnax the schema above should match this one

Comment (masnax) [reply internal/db/update.go:149]: Ah oops, I also didn't remove the foreign key reference from the other table either. Fixed now.
